### ISSUE TITLE
Mod Does Not Replace Flowers

### ISSUE THREAD

**Issue by 91jtezckYoKAoR8GTp6O** [vladislemon/block-replace-mc1.7.10#1]
(Thank you for your work, I am very much excited to see this mod not die)

Tried to replace various flowers with poppies and dandelions but when I create a new world or load an existing one, those flowers still appear generated in the world.

Provided is my config:
[blockreplace.txt](https://github.com/vladislemon/block-replace-mc1.7.10/files/10356403/blockreplace.txt)

(I understand that this is in txt format, GitHub doesn't allow for cfg files)

**Comment by vladislemon** [comment]
There are two issues:

1. You're using nonexistent IDs for blocks.
2. Currently mod lacks support for block metadata.

I'll make update to support metadata.

**Comment by vladislemon** [comment]
Just released new version with metadata support!
For your goal with replacing flowers you can use this config:
```
general {
    # Block ids to replace in format: what-to-replace=replacement [default: ]
    S:replaceMap <
minecraft:red_flower:1=minecraft:red_flower
minecraft:red_flower:2=minecraft:yellow_flower
minecraft:red_flower:3=minecraft:red_flower
minecraft:red_flower:4=minecraft:yellow_flower
minecraft:red_flower:5=minecraft:red_flower
minecraft:red_flower:6=minecraft:yellow_flower
minecraft:red_flower:7=minecraft:red_flower
minecraft:red_flower:8=minecraft:yellow_flower
minecraft:double_plant=minecraft:red_flower
minecraft:double_plant:1=minecraft:yellow_flower
minecraft:double_plant:4=minecraft:red_flower
minecraft:double_plant:5=minecraft:yellow_flower
     >
}
```
But beware of replacing double-block height flowers, it can lead to incorrect block states.

**Comment by 91jtezckYoKAoR8GTp6O** [comment]
> general {
>     # Block ids to replace in format: what-to-replace=replacement [default: ]
>     S:replaceMap <
> minecraft:red_flower:1=minecraft:red_flower
> minecraft:red_flower:2=minecraft:yellow_flower
> minecraft:red_flower:3=minecraft:red_flower
> minecraft:red_flower:4=minecraft:yellow_flower
> minecraft:red_flower:5=minecraft:red_flower
> minecraft:red_flower:6=minecraft:yellow_flower
> minecraft:red_flower:7=minecraft:red_flower
> minecraft:red_flower:8=minecraft:yellow_flower
> minecraft:double_plant=minecraft:red_flower
> minecraft:double_plant:1=minecraft:yellow_flower
> minecraft:double_plant:4=minecraft:red_flower
> minecraft:double_plant:5=minecraft:yellow_flower
>      >
> }

Thank you!

I'll keep the disclaimer in mind.
