### ISSUE TITLE
Please make this dimension specific!!

### ISSUE THREAD

**Issue by brandyyn** [vladislemon/block-replace-mc1.7.10#3]
I'm trying to remove blocks from the overworld and have them spawn in the nether, for example, i'm trying to remove ores from a mod where i can't disable them and i want to add them to the nether using cofh world, but for this to work i need you to add a config to choose which dimensions you want to remove blocks from. i'm begging you for this.

**Comment by vladislemon** [comment]
Hi!
Dimension specific replacement seems useful and easy to implement.
Please wait for next version :)

**Comment by brandyyn** [comment]
Thank you so much, I will test it asap :)

**Comment by brandyyn** [comment]
hi @vladislemon, how can i do metadata? because this causes a crash "ReactorCraft:reactorcraft_block_ore:1,1"

[crash-2024-02-12_00.47.49-client.txt](https://github.com/vladislemon/block-replace-mc1.7.10/files/14234619/crash-2024-02-12_00.47.49-client.txt)

**Comment by brandyyn** [comment]
oh i think i misinterpreted the config, one second

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/8e02e780-a82d-48ed-bf8e-9ca63e38e085)
hmmm doesn't seem to work, what did i do wrong?

> # Configuration file
>
general {
    # Block id to dimension id map, that specifies in what dimensions blocks should be replaced, format: what-to-replace=dimension-ids, example: minecraft:dirt=1,-1 [default: ]
    S:dimensionMap <
	ReactorCraft:reactorcraft_block_ore:1=1
	ReactorCraft:reactorcraft_block_ore:2=1
	ReactorCraft:reactorcraft_block_ore:3=1
	ReactorCraft:reactorcraft_block_ore:4=1
	ReactorCraft:reactorcraft_block_ore:6=1
	ReactorCraft:reactorcraft_block_ore:7=1
	ReactorCraft:reactorcraft_block_ore:8=1
	ReactorCraft:reactorcraft_block_ore:9=1
	ReactorCraft:reactorcraft_block_fluoriteore=1
	ReactorCraft:reactorcraft_block_fluoriteore:1=1
	ReactorCraft:reactorcraft_block_fluoriteore:2=1
	ReactorCraft:reactorcraft_block_fluoriteore:3=1
	ReactorCraft:reactorcraft_block_fluoriteore:4=1
	ReactorCraft:reactorcraft_block_fluoriteore:5=1
	ReactorCraft:reactorcraft_block_fluoriteore:6=1
	ReactorCraft:reactorcraft_block_fluoriteore:7=1
     >

    # Block ids to replace in format: what-to-replace=replacement, example: minecraft:dirt=minecraft:glass [default: ]
    S:replaceMap <
	ReactorCraft:reactorcraft_block_ore:1=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:2=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:3=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:4=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:6=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:7=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:8=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:9=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:1=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:2=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:3=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:4=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:5=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:6=minecraft:stone
     >
}

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/feb8e95d-b058-40e5-a0cc-d02c057e9e04)

**Comment by brandyyn** [comment]
WAIT
I USED THE WRONG DIMENSION ID LMAOOO ONE SEC

**Comment by brandyyn** [comment]
okay nvm still doesn't seem to work :/ 

![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/b25e646c-68ab-43bf-99fe-3804f9bc79e8)

# Configuration file

general {
    # Block id to dimension id map, that specifies in what dimensions blocks should be replaced, format: what-to-replace=dimension-ids, example: minecraft:dirt=1,-1 [default: ]
    S:dimensionMap <
	ReactorCraft:reactorcraft_block_ore:1=0
	ReactorCraft:reactorcraft_block_ore:2=0
	ReactorCraft:reactorcraft_block_ore:3=0
	ReactorCraft:reactorcraft_block_ore:4=0
	ReactorCraft:reactorcraft_block_ore:6=0
	ReactorCraft:reactorcraft_block_ore:7=0
	ReactorCraft:reactorcraft_block_ore:8=0
	ReactorCraft:reactorcraft_block_ore:9=0
	ReactorCraft:reactorcraft_block_fluoriteore=0
	ReactorCraft:reactorcraft_block_fluoriteore:1=0
	ReactorCraft:reactorcraft_block_fluoriteore:2=0
	ReactorCraft:reactorcraft_block_fluoriteore:3=0
	ReactorCraft:reactorcraft_block_fluoriteore:4=0
	ReactorCraft:reactorcraft_block_fluoriteore:5=0
	ReactorCraft:reactorcraft_block_fluoriteore:6=0
	ReactorCraft:reactorcraft_block_fluoriteore:7=0
     >

    # Block ids to replace in format: what-to-replace=replacement, example: minecraft:dirt=minecraft:glass [default: ]
    S:replaceMap <
	ReactorCraft:reactorcraft_block_ore:1=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:2=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:3=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:4=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:6=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:7=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:8=minecraft:stone
	ReactorCraft:reactorcraft_block_ore:9=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:1=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:2=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:3=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:4=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:5=minecraft:stone
	ReactorCraft:reactorcraft_block_fluoriteore:6=minecraft:stone
     >
}

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/e180b537-9401-4e13-b9bd-1e78bee1c939)
just found the only one without a metadata doesn't get replaced either, so i'm not sure what the problem is.

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/5807d7bc-c515-403a-9556-2b3f863ccf7b)
it does seem to be doing something?

**Comment by vladislemon** [comment]
I have tested with ReactorCraft ores, works just fine with your last config, but I don't have those nether versions of ores. Can you give me link to your modpack? I'll test again.

**Comment by brandyyn** [comment]
> I have tested with ReactorCraft ores, works just fine with your last config, but I don't have those nether versions of ores. Can you give me link to your modpack? I'll test again.

![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/d2b3c21c-8361-469c-a32d-c25a7a4c5987)
here's it happening in an instance with just these mods, the nether ores are just it retextured using a texture pack since i wan't to move them to the nether hahaha

i tried with just vanilla blocks and that also didn't work ?
minecraft:sand=minecraft:netherrack
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/a645e999-13d4-4614-93a5-620b24623083)

![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/0fc9aba4-6400-4135-b729-66c391370f2b)

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/a27be48b-e4c9-4ff5-aac3-d2ce365aacda)
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/22d06c9f-f12d-4d04-af1d-23ef1280049f)
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by brandyyn** [comment]
perhaps the replacement is happening too early in the chain of events?

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/e05b2875-e516-48ee-90a9-01d4e658d4fd)
i assume what happens is that the lakes and ores and stuff happens AFTER biome generation/chunk generation so the mod fails to replace those.

**Comment by vladislemon** [comment]
Unlikely, replacement happens at chunk load time, not while world generation. What happened on screenshots looks weird though.

**Comment by brandyyn** [comment]
> Unlikely, replacement happens at chunk load time, not while world generation. What happened on screenshots looks weird though.

obviously these things are generating after the replacement happens, rivers are one of the last things to be generated.

**Comment by brandyyn** [comment]
just did a test, 
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/26803487-aabb-40e3-9c5f-dfaf5d91c743)
this was sand on chunk load, then i left the world and rejoined and it converted to netherrack. firstly, block replacement shouldn't REALLY be happening every time you load a chunk, that's awful for performance. secondly, it should happen as the final thing during chunk generation, even after lakes and ores. that would solve all the problems.

**Comment by vladislemon** [comment]
Initially I made this mod to be capable to replace blocks in already generated chunks, so I can't just change replacement time from chunk load to worldgen. What I can, that is add config option to choose replacement time.

Can you test if rejoining helps with replacement of ReactorCraft ores?

**Comment by brandyyn** [comment]
yes it works with reactorcraft ores when you reload the world, but not on chunk gen
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/f52e1c16-9cb2-460e-82f9-a9d814e87911)


![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/f2c55cbf-e2bc-4923-9f24-703bd6a31b91)
