### ISSUE TITLE
Add option to replace blocks at world generation time

### ISSUE THREAD

**Issue by vladislemon** [vladislemon/block-replace-mc1.7.10#5]
As mentioned in #3, currently block replacement doesn't happen just after world generation and it might be confusing: players forced to reload world to see changes.

**Comment by brandyyn** [comment]
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/4406ed09-a8c9-4970-aca8-4fb5a9c88776)
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/bbf7095b-82e5-49f4-aeb2-15d88f69248d)
![image](https://github.com/vladislemon/block-replace-mc1.7.10/assets/11356565/3734bc66-55b1-4338-9b22-200e4455d17c)

[fml-client-latest.log](https://github.com/vladislemon/block-replace-mc1.7.10/files/14336267/fml-client-latest.log)
